baseURL = "http://localhost:1313/"
title = "Titus Kamau - Cybersecurity Portfolio"
theme = "PaperMod"

[params]
  defaultTheme = "dark"

[[menu.main]]
  name = "home"
  url = "/"
  weight = 5

[[menu.main]]
  name = "projects"
  url = "/cybersecurity/"
  weight = 10

[[menu.main]]
  name = "reports"
  url = "/reports/"
  weight = 15

[[menu.main]]
  name = "blog"
  url = "/blog/"
  weight = 20

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 25

[markup.goldmark.renderer]
  unsafe = true
